//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awtCw2Q3Client.BookServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.BookingService")]
    public interface BookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingService/booking", ReplyAction="http://tempuri.org/BookingService/bookingResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmationNumber")]
        int booking(int specifyRecordNo, string vehicleType, int studentNo, int studentCardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookingService/booking", ReplyAction="http://tempuri.org/BookingService/bookingResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmationNumber")]
        System.Threading.Tasks.Task<int> bookingAsync(int specifyRecordNo, string vehicleType, int studentNo, int studentCardNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookingServiceChannel : awtCw2Q3Client.BookServiceReference.BookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<awtCw2Q3Client.BookServiceReference.BookingService>, awtCw2Q3Client.BookServiceReference.BookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int booking(int specifyRecordNo, string vehicleType, int studentNo, int studentCardNo) {
            return base.Channel.booking(specifyRecordNo, vehicleType, studentNo, studentCardNo);
        }
        
        public System.Threading.Tasks.Task<int> bookingAsync(int specifyRecordNo, string vehicleType, int studentNo, int studentCardNo) {
            return base.Channel.bookingAsync(specifyRecordNo, vehicleType, studentNo, studentCardNo);
        }
    }
}
