//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awtCw2Q3Client.SpecifyTimeAndPlaceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpecifyTimeAndPlaceServiceReference.ISpecifyTimeAndPlace")]
    public interface ISpecifyTimeAndPlace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecifyTimeAndPlace/SpecifyTimeAndPlace", ReplyAction="http://tempuri.org/ISpecifyTimeAndPlace/SpecifyTimeAndPlaceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="specifyEventNo")]
        int SpecifyTimeAndPlace(int studentNo, int orderDate, string orignPlace, string destinationPlace, int studentCardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpecifyTimeAndPlace/SpecifyTimeAndPlace", ReplyAction="http://tempuri.org/ISpecifyTimeAndPlace/SpecifyTimeAndPlaceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="specifyEventNo")]
        System.Threading.Tasks.Task<int> SpecifyTimeAndPlaceAsync(int studentNo, int orderDate, string orignPlace, string destinationPlace, int studentCardNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpecifyTimeAndPlaceChannel : awtCw2Q3Client.SpecifyTimeAndPlaceServiceReference.ISpecifyTimeAndPlace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpecifyTimeAndPlaceClient : System.ServiceModel.ClientBase<awtCw2Q3Client.SpecifyTimeAndPlaceServiceReference.ISpecifyTimeAndPlace>, awtCw2Q3Client.SpecifyTimeAndPlaceServiceReference.ISpecifyTimeAndPlace {
        
        public SpecifyTimeAndPlaceClient() {
        }
        
        public SpecifyTimeAndPlaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpecifyTimeAndPlaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecifyTimeAndPlaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpecifyTimeAndPlaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SpecifyTimeAndPlace(int studentNo, int orderDate, string orignPlace, string destinationPlace, int studentCardNo) {
            return base.Channel.SpecifyTimeAndPlace(studentNo, orderDate, orignPlace, destinationPlace, studentCardNo);
        }
        
        public System.Threading.Tasks.Task<int> SpecifyTimeAndPlaceAsync(int studentNo, int orderDate, string orignPlace, string destinationPlace, int studentCardNo) {
            return base.Channel.SpecifyTimeAndPlaceAsync(studentNo, orderDate, orignPlace, destinationPlace, studentCardNo);
        }
    }
}
